### ISSUE TITLE
Experiment 1b

### ISSUE THREAD

**Issue by nicholas-denis** [nicholas-denis/ppi-testing#5]
Similar to Experiment 0 and Experiment 1, except we will use an open source dataset.

Find an open source tabular regression dataset. X can be numerical, categorical, boolean, etc, Y is numerical (floats).
Make sure to spend a good amount of time finding a good dataset, we will use it for many experiments.

- We can simulate distribution shift by doing things like stratified sampling in our dataset to split the data for training the ML model and for the PPI component.
- Example, if age/race/sex is a field, we could partition data based on race or various age brackets, and then sample disproportionately to create two non-identical distributions

- Make sure that we process the input features, X, appropriately (checkout scikit learn Transforms like Categorical Encoder, RobustScaler, MinMaxScaler, StandardScaler, etc)
- The dataset will need to be split into 4 subsets: (train, val) and (ppi_labelled, ppi_unlablled), where we train the ML model using train, and use val to do hyper-tuning. train and val should be from the same distribution, but ppi_* should be from another (except when we are redoing Experiment 0, which all data is from the same distribution).

- [ ] add informative plots
- [ ] cover the bias of the resulting estimate
- [ ] cover the coverage
- [ ] cover the size of confidence intervals

**Comment by Aspiire** [comment]
Closing due to document existing.
