### ISSUE TITLE
helper modules: ppi.py, distributions.py, ml_models.py

### ISSUE THREAD

**Issue by nicholas-denis** [nicholas-denis/ppi-testing#9]
These scripts will hold all the code relevant for their appropriate functionality

distributions.py:
- [x] could be overkill, but we can write functions to sample from a particular distribution (N(m,s), Gamma(a,b), etc)
- [x] I know in some languages (Julia), you can create "distribution" objects, like my_normal = build_a_normal(0,1), and then you can just sample from it using a method like my_sample = my_normal.sample(1000).... IF you can find something like this in python, we could also use this... but we should do some simple tests to see what is more efficient
- [x] make sure the functions for these functions make use of the variables set in the yaml config file
- [x] in main.py import these functions
- [x] test there functionality

ml_models.py:
- [x] have the scikitlearn train_test_split here (just a helper function)
- [x] this is where we build a models, etc
- [x] make sure the functions for these functions make use of the variables set in the yaml config file
- [x] in main.py import these functions
- [x] test there functionality

ppi.py
- [x] put all ppi related functions here
- [x] You haven't yet, but now we have to generalize and have the ability to set the lambda (I think its lambda) parameter in PPI (PPI++). On one scale (0, i think) you get PPI, and default value is 1.0, which means use ppi++... check documentation, I may be mixed up but just make sure we represent these options. Feel free to have the function default to 0 or 1 or whatever.. either way, we will do experiments with PPI and PPI++ (and later active statistical inference)
- [x] put all the stuff where we get point estimates, the lower bounds, the upper bounds, the ci's etc
- [x] make sure the functions for these functions make use of the variables set in the yaml config file
- [x] in main.py import these functions
- [x] test there functionality

**Comment by Aspiire** [comment]
all the helpers are written now, i put them in a single .py for now, but i will soon split them, they should all be working

**Comment by Aspiire** [comment]
i've written classes before for classes with regards to distributions and sampling, im not sure if its worth the extra work to incorporate it with the yaml file since everything here is just functional programming rather than OOP. It mayyyy be worth looking at? Though writing functions for sampling new distributions isn't really hard at the moment, I just use a dictionary parser right now. If we think the dictionary parser is bad (I don't like the global variable portion anyways), then I can convert it for some future proofing.
